[package]
name = "st-nucleo-f401re"
version = "0.1.0"
license.workspace = true
edition.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-stm32 = { workspace = true, features = ["stm32f401re"] }
ariel-os-debug = { workspace = true, features = ["rtt-target"] }
ariel-os-rt.workspace = true
