[package]
name = "benchmark"
version = "0.1.0"
license.workspace = true
edition.workspace = true

publish = false

[lints]
workspace = true

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = ["bench"] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }
