[package]
name = "ariel-os-boards"
version.workspace = true
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
cfg-if.workspace = true
linkme.workspace = true

ariel-os-rt = { path = "../ariel-os-rt" }

ai-c3 = { optional = true, path = "ai-c3" }
espressif-esp32-c6-devkitc-1 = { optional = true, path = "espressif-esp32-c6-devkitc-1" }
espressif-esp32-s3-wroom-1 = { optional = true, path = "espressif-esp32-s3-wroom-1" }
espressif-esp32-wroom-32 = { optional = true, path = "espressif-esp32-wroom-32" }
dwm1001 = { optional = true, path = "dwm1001" }
microbit = { optional = true, path = "microbit" }
microbit-v2 = { optional = true, path = "microbit-v2" }
nrf52840-mdk = { optional = true, path = "nrf52840-mdk" }
nrf52840dk = { optional = true, path = "nrf52840dk" }
nrf52dk = { optional = true, path = "nrf52dk" }
nrf5340dk = { optional = true, path = "nrf5340dk" }
st-nucleo-f401re = { optional = true, path = "st-nucleo-f401re" }
st-nucleo-wb55 = { optional = true, path = "st-nucleo-wb55" }
rpi-pico = { optional = true, path = "rpi-pico" }
particle-xenon = { optional = true, path = "particle-xenon" }
st-nucleo-h755zi-q = { optional = true, path = "st-nucleo-h755zi-q" }

[features]
# Allows to have no boards selected, useful to run platform-independent tooling
no-boards = []

ai-c3 = ["dep:ai-c3"]
dwm1001 = ["dep:dwm1001"]
espressif-esp32-c6-devkitc-1 = ["dep:espressif-esp32-c6-devkitc-1"]
espressif-esp32-s3-wroom-1 = ["dep:espressif-esp32-s3-wroom-1"]
espressif-esp32-wroom-32 = ["dep:espressif-esp32-wroom-32"]
microbit = ["dep:microbit"]
microbit-v2 = ["dep:microbit-v2"]
nrf52840-mdk = ["dep:nrf52840-mdk"]
nrf52840dk = ["dep:nrf52840dk"]
nrf52dk = ["dep:nrf52dk"]
nrf5340dk = ["dep:nrf5340dk"]
particle-xenon = ["dep:particle-xenon"]
rpi-pico = ["dep:rpi-pico"]
rpi-pico-w = ["dep:rpi-pico", "rpi-pico?/rpi-pico-w"]
st-nucleo-f401re = ["dep:st-nucleo-f401re"]
st-nucleo-h755zi-q = ["dep:st-nucleo-h755zi-q"]
st-nucleo-wb55 = ["dep:st-nucleo-wb55"]
