[package]
name = "microbit"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true

ariel-os-debug.workspace = true
ariel-os-rt.workspace = true

nrf51 = { path = "../nrf51" }
