[package]
name = "espressif-esp32-c3-lcdkit"
version = "0.1.0"
license.workspace = true
edition = "2021"

[dependencies]
riot-rs-rt = { workspace = true, features = ["_esp32c3"] }
riot-rs-debug.workspace = true
