[package]
name = "testing"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ariel-os = { path = "../../src/ariel-os" }
ariel-os-boards = { path = "../../src/ariel-os-boards" }

[dev-dependencies]
embedded-test = { workspace = true }

[[test]]
name = "example_test"
harness = false
