[package]
name = "stm32f4xx"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
bare-metal = "1.0.0"
cortex-m.workspace = true
stm32f4xx-hal = "0.21"
#features = [ "rt" ]

[features]
stm32f401 = ["stm32f4xx-hal/stm32f401"]
