[package]
name = "ariel-os-threads"
version = "0.1.0"
edition.workspace = true
license.workspace = true
description = "generic embedded scheduler & IPC"
include = ["src/**/*", "README.md"]
repository.workspace = true

[lints]
workspace = true

[dependencies]
cfg-if.workspace = true
critical-section.workspace = true
linkme = { workspace = true }
paste.workspace = true
ariel-os-debug.workspace = true
ariel-os-runqueue.workspace = true
ariel-os-utils.workspace = true
static_cell.workspace = true

defmt = { workspace = true, optional = true }

[target.'cfg(context = "esp32")'.dependencies]
esp-hal = { workspace = true, features = ["esp32"] }

[target.'cfg(context = "esp32c3")'.dependencies]
esp-hal = { workspace = true, features = ["esp32c3"] }

[target.'cfg(context = "esp32c6")'.dependencies]
esp-hal = { workspace = true, features = ["esp32c6"] }

[target.'cfg(context = "esp32s3")'.dependencies]
esp-hal = { workspace = true, features = ["esp32s3"] }
static_cell = { workspace = true, optional = true }

[target.'cfg(context = "cortex-m")'.dependencies]
# cortex-m specifics
cortex-m.workspace = true
cortex-m-rt.workspace = true
cortex-m-semihosting.workspace = true
panic-semihosting = { version = "0.6.0", features = ["exit"] }

[target.'cfg(context = "rp2040")'.dependencies]
static_cell = { workspace = true, optional = true }
rp-pac = { workspace = true, optional = true }
embassy-rp = { workspace = true, optional = true }

[features]
defmt = ["dep:defmt", "ariel-os-runqueue/defmt"]
multi-core = [
  "dep:static_cell",
  "dep:rp-pac",
  "dep:embassy-rp",
  "embassy-rp/fifo-handler",
]
core-affinity = ["multi-core"]
