[package]
name = "ariel-os-chips"
version = "0.1.0"
license.workspace = true
edition.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
stm32f4xx = { optional = true, path = "stm32f4xx" }

[features]
stm32f401 = ["stm32f4xx/stm32f401"]
