[package]
name = "nrf5340dk"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
cortex-m.workspace = true
cortex-m-rt.workspace = true

ariel-os-debug.workspace = true

nrf5340 = { path = "../nrf5340" }
